<!DOCTYPE html>
<html lang="nl-NL">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Omid Barza frontend test for Youwe Co.">
    <title>CuraNu Social Intranet</title>
    <?php include('app/head.phtml') ?>
</head>
<body id="home_page" class="index home">
    <!-- <<< Page Wrapper -->
    <div class="page-wrapper">
        <?php include('app/header.phtml') ?>

        <!-- <<< Main Area -->
        <section class="main">
            <div class="container row masonry">
                <?php include('app/main/accordion.phtml') ?>
                <?php include('app/main/evenementen.phtml') ?>
                <?php include('app/main/news.phtml') ?>
                <?php include('app/main/widget.phtml') ?>
                <?php include('app/main/direct-neer.phtml') ?>
                <?php include('app/main/blogs.phtml') ?>
                <?php include('app/main/kwaliteitshandboek.phtml') ?>
                <?php include('app/main/peilingen.phtml') ?>
                <?php include('app/main/links.phtml') ?>
                <?php include('app/main/phone-book.phtml') ?>
                <?php include('app/main/microblog.phtml') ?>
                <?php include('app/main/groepen.phtml') ?>
            </div>
        </section>
        <!-- >>> Main Area -->
        
        <footer class="m3"></footer>
    </div>
    <!-- >>> Page Wrapper -->
</body>
</html>
