<form id="contact_form" action="" method="post">
    <div class="field-wrapper col-12">
        <label class="col-2 d-ib font-bold name-label" for="name">Naam: </label>
        <input type="text" name="name" class="input-field col-3"/>
    </div>
    <div class="field-wrapper col-12">
        <label class="col-2 d-ib font-bold email-label" for="email">Email: </label>
        <input type="text" name="email" class="input-field col-3"/>
    </div>
    <div class="field-wrapper col-12">
        <label class="col-2 d-ib font-bold subject-label" for="subject">Onderwerp: </label>
        <input type="text" name="subject" class="input-field col-3"/>
    </div>
    <div class="field-wrapper col-12">
        <label class="col-2 d-ib font-bold description-label" for="description">Bericht: </label>
        <textarea type="text" name="description" class="textarea-field col-10"></textarea>
    </div>
    <div class="field-wrapper col-12 t-right mt2">
        <button class="submit-btn mr2" type="submit">Verstuur</button>
    </div>
</form>
