<!-- <<< Content aria -->
<div class="content col-10">
    <h2 class="mt0">Contact pagina</h2>
    <p class="contact-paragraph">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque convallis, magna nec efficitur tempor, dui eros fringilla tellus, vitae
consequat augue dolor at mauris. Nunc tempor rutrum dolor, sit amet scelerisque lacus feugiat non. Maecenas a tincidunt justo, ac
blandit arcu. Sed nec congue ex. Nullam pulvinar libero eu dolor congue commodo. Nam sed pharetra orci. Nunc ultrices sit amet magna
non vestibulum. Morbi ut dignissim quam. Etiam eget pellentesque nisi.
    </p>
    <?php include('_contact.form.phtml') ?>
</div>
<!-- >>> Content aria -->
