<!-- <<< Header Main Section -->
<section class="header-main container row">
    <div class="logo-wrapper col-6 mt1 mb1">
        <a href="/" class="logo flex-item d-f f-align-bottom f-justify-left">
            <img src="assets/image/curanu-logo.png" alt="CuraNu"/>
            <h1 class="m0 hidden-sm"><span class="name">Cura</span>Nu <span class="d-b slogan">Zorg en welzijn</span></h1>
            <span class="interanet d-ib mx2 hidden-sm">Interanet</span>
        </a>
    </div>
</section>
<!-- >>> Header Main Section -->
