<!-- <<< Navigation Menu -->
<section class="nav">
    <nav class="container navigation row my2 py1">
        <ul class="menu col-8">
            <li class="py1 px2 d-ib pl0"><a href="#" class="text-white font-bold">Artikelen</a></li>
            <li class="py1 px2 d-ib"><a href="#" class="text-white font-bold">Nieuws</a></li>
            <li class="py1 px2 d-ib"><a href="#" class="text-white font-bold">Evenementen</a></li>
            <li class="py1 px2 d-ib"><a href="#" class="text-white font-bold">Kwaliteitshandboek</a></li>
        </ul>
        <div class="top-search col-4 f-right">
            <form id="header_search" action="/" method="get">
                <input type="text" name="q" class="input-field" placeholder="Search site here..."/>
                <button class="btn-icon search" type="submit"></button>
            </form>
        </div>
    </nav>
</section>
<!-- >>> Navigation Menu -->
