<!-- <<< Header Top -->
<section class="header-top container">
    <div class="row top-wrapper">
        <div class="col-10 mb0">
            <nav class="top-links">
                <a href="#" class="link p1 d-ib">Groepen</a>
                <a href="#" class="link p1 d-ib">Contact</a>
                <a href="#" class="link p1 d-ib">FAQ</a>
                <a href="#" class="link p1 d-ib">Smoelenboek</a>
                <a href="#" class="link p1 d-ib">Microblog</a>
                <a href="#" class="link p1 d-ib">Over ons</a>
            </nav>
        </div>
        <div class="col-2 my0 t-right f-right hidden-sm">
            <span class="btn-icon gear mt1 b-radius-1"></span>
            <span class="btn-icon bell mt1 b-radius-1"></span>
        </div>
        <div class="col-12 border my0"></div>
    </div>
</section>
<!-- >>> Header Top -->
