<!-- <<< Accordion -->
<div class="col-4 col-4-md">
    <div class="box accordion">
        <div class="accordion-item">
            <div id="accordion_header_1" class="accordion-header d-f f-align-center f-justify-between" data-content="#accordion_content_1">
                <h4 class="title d-ib my0 mx2 font-bold">Accordion 1</h4>
                <span class="btn-icon arrow-right"></span>
            </div>
            <div id="accordion_content_1" class="accordion-content">
                <p class="m0 font-size-1 p2">Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttito.</p>
            </div>
        </div>

        <div class="accordion-item">
            <div id="accordion_header_2" class="accordion-header d-f f-align-center f-justify-between" data-content="#accordion_content_2">
                <h4 class="title d-ib my0 mx2 font-bold">Accordion 2</h4>
                <span class="btn-icon arrow-right"></span>
            </div>
            <div id="accordion_content_2" class="accordion-content">
                <p class="m0 font-size-1 p2">Accordion 1 Accordion 1 Accordion 1 Accordion 1 Accordion 1 Accordion 1 Accordion 1 Accordion 1 Accordion 1 Accordion 1</p>
            </div>
        </div>

        <div class="accordion-item">
            <div id="accordion_header_3" class="accordion-header d-f f-align-center f-justify-between" data-content="#accordion_content_3">
                <h4 class="title d-ib my0 mx2 font-bold">Accordion 3</h4>
                <span class="btn-icon arrow-right"></span>
            </div>
            <div id="accordion_content_3" class="accordion-content">
                <p class="m0 font-size-1 p2">Accordion 3 Accordion 3Accordion 3Accordion 3Accordion 3Accordion 3Accordion 3Accordion 3Accordion 3Accordion 3Accordion 3</p>
            </div>
        </div>
    </div>
</div>
<!-- >>> Accordion -->
