<!-- <<< blogs -->
<div class="col-4">
    <div class="box blogs">
        <div class="header d-f f-align-center f-justify-between">
            <span class="btn-icon edit"></span>
            <h4 class="title d-ib my0 mx2 font-bold arrow-down">Blogs</h4>
            <span class="btn-icon close"></span>
        </div>
        <div class="content p2 py1">
            <section class="posts">
                <article>
                    <div class="d-f f-justify-between f-align-center">
                        <div class="author d-f f-justify-start f-align-center">
                            <img src="assets/image/author.png" />
                            <h6 class="author ml2">Ria de Vries 
                                <span class="publish-date font-size-0 font-lighter d-b">12/04/2016</span>
                            </h6>
                        </div>
                        <span class="icon-like like">0</span>
                    </div>
                    <h6 class="m0">Samenleving</h6>
                    <p class="font-size-1 mt0">
                        Nieuwe compagne CuraNu gisteren van start gogaan
                    </p>
                </article>
            </section>
        </div>
        <div class="footer d-f f-justify-between f-align-center font-size-1">
            <a href="#" class="ml2">Meer blogs</a>
            <span class="btn-icon arrow-right"></span>
        </div>
    </div>
</div>
<!-- >>> Blogs -->
