<!-- <<< Direct Naar -->
<div class="col-4 col-4-md">
    <div class="box direct-naar">
        <div class="header d-f f-align-center f-justify-between">
            <span class="btn-icon e-link"></span>
            <h4 class="title d-ib my0 font-bold arrow-down-header">Direct Naar</h4>
            <span class="btn-icon close"></span>
        </div>
        <div class="content p2">
            <ul class="m0">
                <li class="pb1 px2">
                    <span class="d-ib pr3 img t-center"><img src="assets/image/youforce.png" alt="Youforce"/></span>
                    <span class="d-ib font-bold font-size-1">Youforce</span>
                </li>
                <li class="py1 px2">
                    <span class="d-ib pr3 img t-center"><img src="assets/image/curanu-logo.png" alt="Youforce"/></span>
                    <span class="d-ib font-bold font-size-1">MIP-meldingen</span>
                </li>
                <li class="pt1 px2 mt1">
                    <span class="d-ib pr3 img t-center"><img src="assets/image/topdesk.png" alt="Youforce"/></span>
                    <span class="d-ib font-bold font-size-1">Topdesk</span>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- >>> Direct Naar -->
                