<!-- <<< Evenementen -->
<div class="col-4 col-4-md">
    <div class="box evenementen">
        <div class="header d-f f-align-center f-justify-between">
            <span class="btn-icon calendar"></span>
            <h4 class="title d-ib my0 font-bold arrow-down-header">Evenementen</h4>
            <span class="btn-icon close"></span>
        </div>
        <div class="content p2">
            <ul class="m0">
                <li class="pb2">
                    <span class="d-ib pr3 img t-center font-size-1">10/12/2016</span>
                    <span class="d-ib font-bold font-size-1">Zorgmarthon</span>
                </li>
                <li class="py2">
                        <span class="d-ib pr3 img t-center font-size-1">12/12/2016</span>
                    <span class="d-ib font-bold font-size-1">Beurs</span>
                </li>
                <li class="pt2">
                        <span class="d-ib pr3 img t-center font-size-1">30/12/2016</span>
                    <span class="d-ib font-bold font-size-1">Onze zorgevenement</span>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- >>> Evenementen -->
