<!-- <<< Groepen -->
<div class="col-4">
    <div class="box groepen">
        <div class="header d-f f-align-center f-justify-between">
            <span class="btn-icon groups"></span>
            <h4 class="title d-ib my0 mx2 font-bold arrow-down">Groepen</h4>
            <span class="btn-icon close"></span>
        </div>
        <div class="content p2 py1">
            <ul class="m0">
                <li class="d-f f-justify-start f-align-center">
                    <img src="assets/image/group-1.png" />
                    <h6 class="author ml2">HRM</h6>
                </li>
                <li class="d-f f-justify-start f-align-center">
                    <img src="assets/image/group-2.png" />
                    <h6 class="author ml2">Marketing</h6>
                </li>
            </ul>
        </div>
        <div class="footer d-f f-justify-between f-align-center font-size-1">
            <a href="#" class="ml2">Meer groepen</a>
            <span class="btn-icon arrow-right"></span>
        </div>
    </div>
</div>
<!-- >>> Groepen -->
