<!-- <<< Kwaliteitshandboek -->
<div class="col-4">
    <div class="box kwaliteitshandboek">
        <div class="header d-f f-align-center f-justify-between">
            <span class="btn-icon report"></span>
            <h4 class="title d-ib my0 font-bold arrow-down">Kwaliteitshandboek</h4>
            <span class="btn-icon close"></span>
        </div>
        <div class="content p2 py1">
            <ul class="m0">
                <li class="py2 row">
                    <div class="name d-b font-bold font-size-1">Klachtenprocedure</div>
                    <span class="d-b font-size-0 col-9 m0 font-italic">bijgewerk / 18-04-2016</span>
                </li>
                <li class="py2 row">
                    <div class="name d-b font-bold font-size-1">Periodieke test gebruikersgroepen</div>
                    <span class="d-b font-size-0 col-9 m0 font-italic">bijgewerk / 10-02-2016</span>
                </li>
                <li class="py2 row">
                    <div class="name d-b font-bold font-size-1">Dienstrichtlijn tweede niveau</div>
                    <span class="d-b font-size-0 col-9 m0 font-italic">bijgewerk / 09-05-2016</span>
                </li>
            </ul>
        </div>
        <div class="footer d-f f-justify-between f-align-center font-size-1">
            <a href="#" class="ml2">Naar kwaliteitshandboek</a>
            <span class="btn-icon arrow-right"></span>
        </div>
    </div>
</div>
<!-- >>> Kwaliteitshandboek -->
