<!-- <<< Links -->
<div class="col-4 col-4-md">
    <div class="box links">
        <div class="header d-f f-align-center f-justify-between">
            <span class="btn-icon report"></span>
            <h4 class="title d-ib my0 mx2 font-bold arrow-down font-size-1">Mijn Links</h4>
            <span class="btn-icon close"></span>
        </div>
        <div class="content p2 py1">
            <ul class="m0">
                <li class="py2 row">
                    <div class="font-size-0 font-bold">Zorggroep.nl</div>
                </li>
                <li class="py2 row">
                    <div class="font-size-0 font-bold">zorgvisie.nl</div>
                </li>
                <li class="py2 row">
                    <div class="font-size-0 font-bold">medicalfacts.nl</div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- >>> Links -->
