<!-- <<< Microblog -->
<div class="col-4 col-4-md">
    <div class="box microblog">
        <div class="header d-f f-align-center f-justify-between">
            <span class="btn-icon edit"></span>
            <h4 class="title d-ib my0 mx2 font-bold arrow-down">Microblog</h4>
            <span class="btn-icon close"></span>
        </div>
        <div class="content p2">
            <form id="microblog_post" action="/" method="get" class="my1">
                <textarea name="post" class="text-area"></textarea>
                <div class="btn-group d-f f-justify-between mt1 mb3">
                    <div>
                        <a href="#" class="insert insert-image d-ib"></a>
                        <a href="#" class="insert insert-link d-ib"></a>
                    </div>
                    <button class="submit" type="submit">Plaats</button>
                </div>
            </form>

            <section class="posts">
                <article>
                    <div class="d-f f-justify-between f-align-center">
                        <div class="author d-f f-justify-start f-align-center">
                            <img src="assets/image/author.png" />
                            <h6 class="author ml2">Ria de Vries <span class="publish-date font-size-0 font-lighter d-b">12/09/2016&nbsp;-&nbsp;11:10</span></h6>
                        </div>
                        <span class="icon-like like">1</span>
                    </div>
                    <p class="font-size-1 mt0">
                        Nieuwe compagne CuraNu gisteren van start gogaan
                        <img class="d-b my2" src="assets/image/micro-blog-post.png" />
                    </p>
                    <p class="font-size-1 font-bold">Lees meer en reacties (0)</p>
                </article>
            </section>
        </div>
        <div class="footer d-f f-justify-between f-align-center font-size-1">
            <a href="#" class="ml2">Toon meer</a>
            <span class="btn-icon arrow-right"></span>
        </div>
    </div>
</div>
<!-- >>> Microblog -->
