<!-- <<< News -->
<div class="col-4">
    <div class="box news">
        <div class="header d-f f-align-center f-justify-between">
            <span class="btn-icon news"></span>
            <h4 class="title d-ib my0 mx2 font-bold arrow-down">Nieuws</h4>
            <span class="btn-icon close"></span>
        </div>
        <div class="content p2">
            <ul class="m0">
                <li class="py2 row">
                    <img src="assets/image/laptop.png" class="col-3 m0"/>
                    <div class="col-9 m0 row f-right">
                        <span class="d-b font-size-1 col-9 m0">29/02/2016</span>
                        <span class="icon-like like col-3 f-right m0">3</span>
                    </div>
                    <div class="name d-b font-bold font-size-1">Zorgmarthon</div>
                </li>
                
                <li class="py2 row">
                    <img src="assets/image/nurse.png" class="col-3 m0"/>
                    <div class="col-9 m0 row f-right">
                        <span class="d-b font-size-1 col-9 m0">29/02/2016</span>
                        <span class="icon-like like col-3 f-right m0">0</span>
                    </div>
                    <div class="name d-b font-bold font-size-1">VIO erkend als theoretisch goed</div>
                </li>
                
                <li class="pt2 row">
                    <img src="assets/image/handshake.png" class="col-3 m0"/>
                    <div class="col-9 m0 row f-right">
                        <span class="d-b font-size-1 col-9 m0">29/02/2016</span>
                        <span class="icon-like like col-3 f-right m0">2</span>
                    </div>
                    <div class="name d-b font-bold font-size-1">Commissiebrief over nieuwe Wlz</div>
                </li>
            </ul>
        </div>
        <div class="footer d-f f-justify-between f-align-center font-size-1">
            <a href="#" class="ml2">Meer nieuws</a>
            <span class="btn-icon arrow-right"></span>
        </div>
    </div>
</div>
<!-- >>> News -->
