<!-- <<< Phone Book -->
<div class="col-4 col-4-md">
    <div class="box telefoonboek p2">
        <div class="header"><h4 class="m0 text-white">Telefoonboek</h4></div>
        <p class="font-size-0 text-white">Vind collega's op naam, trefwoord functie, etc.</p>
        <form id="telefoonboek_search" action="/" method="get" class="my1">
            <input type="text" name="telephone" class="input-field" placeholder="Enter phone number..."/>
            <button class="btn-icon search" type="submit"></button>
        </form>
    </div>
</div>
<!-- >>> Phone Book -->
